name: Release Mod

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Extract version from Gradle
        id: get_version
        run: |
          VERSION=$(grep -oP 'modVersion\s*=\s*\K[^"]+' gradle.properties)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build JAR
        run: ./gradlew clean build

      - name: Publish to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth
          modrinth-id: "yet-another-air-drop"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # CurseForge
#          curseforge-id: "1267814"
#          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # GitHub
          github-tag: ${{ steps.get_version.outputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Files to upload (exclude dev/sources/javadoc)
          files: |
            build/libs/*${{ steps.get_version.outputs.version }}*.jar

          name: "Yet Another Air Drop ${{ steps.get_version.outputs.version }}"
          version: ${{ steps.get_version.outputs.version }}
          version-type: release
          changelog-file: CHANGELOG*

          loaders: |
            fabric
            
          game-versions: |
            1.21.4

          dependencies: |
            fabric@0.118.5+1.21.4(required){modrinth:IXeiAH6H}{curseforge:6284237}#(ignore:github)
            fabric-kotlin-language@1.11.0+kotlin.2.0.0(required){modrinth:afsFajDC}{curseforge:5361341}#(ignore:github)
            modmenu-badges-lib@2023.6.1(embedded){modrinth:n5smDDrP}{curseforge:4758382}#(ignore:github)
            ducky-updater-lib@2024.10.2(embedded){modrinth:WCwN1ld7}{curseforge:5856269}#(ignore:github)

          java: |
            21

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: Trigger post‑release bot
        env:
          WEBHOOK_URL: ${{ secrets.BOT_WEBHOOK }}
        run: |
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "action": "released",
              "version": "${{ steps.get_version.outputs.version }}",
              "tag":  "${{ github.event.release.tag_name }}",
              "url":  "${{ github.event.release.html_url }}"
            }'